### ISSUE TITLE
[FEATURE REQUEST] Add support for refresh credentials endpoint

### ISSUE THREAD

**Issue by johnnysohn** [apache/polaris#508] opened 2024-12-04 21:50 UTC
### Is your feature request related to a problem? Please describe.

With the release of Iceberg [1.7.0](https://github.com/apache/iceberg/releases/tag/apache-iceberg-1.7.0), we now have a way (new API) to refresh vended credentials. 

Specifically [LoadCredentialsResponse](https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.yaml#L3165) and an API endpoint has been added to support refreshing vended credentials.

### Describe the solution you'd like

Please implement these new REST spec on Polaris to support refreshing vended credentials. If the Polaris team is resource constrained on providing this in a timely manner, we can help out with the dev effort on this.

**Comment by adutra** [comment] 2024-12-05 10:45
This is a duplicate of #464.

**Comment by collado-mike** [comment] 2024-12-11 19:01
Closing as dupe. Work can continue on the linked issue

**Closed by collado-mike** 2024-12-11 19:01 UTC
Labels: enhancement
